steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'version=${_VERSION}', '-t', 'us-docker.pkg.dev/$PROJECT_ID/${_IMG}:${_VERSION}', '-f', '${_DOCKERFILE}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'us-docker.pkg.dev/${PROJECT_ID}/${_IMG}:${_VERSION}', 'us-docker.pkg.dev/${PROJECT_ID}/${_IMG}:latest']

substitutions:
  _IMG:
  _VERSION:
  _DOCKERFILE: 'Dockerfile.gcp'

images: 
  - 'us-docker.pkg.dev/${PROJECT_ID}/${_IMG}:${_VERSION}'
  - 'us-docker.pkg.dev/${PROJECT_ID}/${_IMG}:latest'

tags:
- '${_VERSION}'
