#                           PUBLIC DOMAIN NOTICE
#              National Center for Biotechnology Information
#  
# This software is a "United States Government Work" under the
# terms of the United States Copyright Act.  It was written as part of
# the authors' official duties as United States Government employees and
# thus cannot be copyrighted.  This software is freely available
# to the public for use.  The National Library of Medicine and the U.S.
# Government have not placed any restriction on its use or reproduction.
#   
# Although all reasonable efforts have been taken to ensure the accuracy
# and reliability of the software and data, the NLM and the U.S.
# Government do not and cannot warrant the performance or results that
# may be obtained by using this software or data.  The NLM and the U.S.
# Government disclaim all warranties, express or implied, including
# warranties of performance, merchantability or fitness for any particular
# purpose.
#   
# Please cite NCBI in any work or product based on this material.

FROM alpine:3.14
ARG version

LABEL Description="NCBI ElasticBLAST Cloud Job Submission Module"
LABEL Version=${version}
LABEL Vendor="NCBI/NLM/NIH"
LABEL Maintainer=camacho@ncbi.nlm.nih.gov

COPY requirements.txt .
RUN sed -i '/elastic-blast/d' requirements.txt

COPY run.sh /usr/bin/

RUN chmod +x /usr/bin/run.sh && \
    apk -U upgrade && \
    apk add --no-cache bash python3 py3-pip py3-wheel && \
    pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.txt && \
    mkdir -p /var/elastic-blast && \
    rm -rf /var/cache/apk/* requirements.txt

COPY src/ /var/elastic-blast/src/
COPY bin/ /var/elastic-blast/bin/
COPY requirements/ /var/elastic-blast/requirements/
COPY setup.py /var/elastic-blast/setup.py
COPY setup.cfg_cloud /var/elastic-blast/setup.cfg

WORKDIR /var/elastic-blast

RUN pip3 install . -r requirements/base.txt

CMD ["run.sh", "-h"]
