steps:
- name: 'us-docker.pkg.dev/${PROJECT_ID}/${_IMG}:${_TAG}'
  args: ['aws', '--version']
- name: 'us-docker.pkg.dev/${PROJECT_ID}/${_IMG}:${_TAG}'
  args: ['aws', 's3', '--no-sign-request', 'ls', 's3://ncbi-blast-databases/']
- name: 'us-docker.pkg.dev/${PROJECT_ID}/${_IMG}:${_TAG}'
  args: ['fasta_split.py', '--help']
- name: 'us-docker.pkg.dev/${PROJECT_ID}/${_IMG}:${_TAG}'
  args: ['run.sh', '-h']
# This doesn't work due to lack of credentials
#- name: 'us-docker.pkg.dev/${PROJECT_ID}/${_IMG}:${_TAG}'
#  args: ['run.sh', '-i', 's3://elasticblast-test/queries/hepatitis.fsa.gz', '-o', 's3://elasticblast-test/']

substitutions:
  _IMG:
  _TAG:
